name: fairbid_flutter
description: Flutter plugin for FairBid 2 SDK
version: 0.5.0
homepage: https://github.com/ukasz123/fairbid_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.fairbid_flutter
        pluginClass: FairBidFlutterPlugin
      ios:
        pluginClass: FairBidFlutterPlugin
