name: fairbid_flutter
description: Unofficial Flutter plugin for FairBid SDK - the advertisement mediation platform. Supports banner, interstitial and rewarded video ads.
version: 0.8.0-dev.5
homepage: https://github.com/ukasz123/fairbid_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.1.7

  rxdart: ">=0.23.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  build_version: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.fairbid_flutter
        pluginClass: FairBidFlutterPlugin
      ios:
        pluginClass: FairBidFlutterPlugin
